#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: false
#  flyway:
#    enabled: true
server:
  address: localhost
eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://${EUREKA_ADDRESS}/eureka/

    register-with-eureka: true
    fetch-registry: true