#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: false
#  flyway:
#    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8866/eureka/