#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: false
#  flyway:
#    enabled: true
spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo

eureka:
  instance:
    prefer-ip-address: true