eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ADDRESS}/eureka/
    register-with-eureka: false
    fetch-registry: true



spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: clients
          uri: lb://CLIENTS
          predicates:
          - Path=/**
