server:
  port:
    8000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: security
          uri: lb://security
          order: 1
          predicates:
            - Path=/login,/registration,/logout
          filters:
            - AddRequestParameter=failure,error,pass,exists,incorrect
        - id: clients
          uri: lb://clients
          order: 2
          predicates:
            - Path=/**

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_ADDRESS}
          defaultBrokerPort: ${KAFKA_PORT}

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway

custom:
  kafka:
    address: ${KAFKA_ADDRESS}:${KAFKA_PORT}
    topics:
      request: ${TOPIC_REQUEST}
      response: ${TOPIC_RESPONSE};

jwt:
  cookie:
    name: JwtCookie