server:
  port:
    8000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ADDRESS}/eureka/
    fetch-registry: true
    register-with-eureka: true



spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: clients
          uri: lb://clients
          predicates:
          - Path=**

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway
