server:
  port:
    8000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: security
          uri: lb://security
          predicates:
            - Path=/login
            - Path=/register
        - id: clients
          uri: lb://clients
          predicates:
            - Path=/**

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway
