server:
  port:
    8000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: security
          uri: lb://security
          order: 1
          predicates:
            - Path=/login,/registration,/logout
          filters:
            - AddRequestParameter=failure,error,pass,exists,incorrect
            - RewriteResponseHeader=X-Original-Location, (?<location>.*), http://localhost:8000
        - id: clients
          uri: lb://clients
          order: 2
          predicates:
            - Path=/**

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway
