spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_ADDRESS}/${MONGO_DB}?authSource=admin&authMechanism=SCRAM-SHA-1
  data:
    mongodb:
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_ADDRESS}/${MONGO_DB}?authSource=admin&authMechanism=SCRAM-SHA-1

  jackson:
    serialization:
      write-dates-as-timestamps: false

custom:
  gateway:
    address: ${LOCALHOST_GATEWAY_ADDRESS}
