#spring:
#  application:
#    name: clients
#
#  profiles:
#    active: dev
#
#  config:
#    import: optional:configserver:http://localhost:8888
#
#  cloud:
#    config:
#      fail-fast: true
#
#  devtools:
#    add-properties: false
server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ADDRESS}/eureka/

    register-with-eureka: true
    fetch-registry: true