spring:
  datasource:
    url: jdbc:mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_ADDRESS}/${MONGO_DB}
  data:
    mongodb:
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      uri: mongodb://${MONGO_ADDRESS}/${MONGO_DB}

  jackson:
    serialization:
      write-dates-as-timestamps: false

custom:
  gateway:
    address: ${LOCALHOST_GATEWAY_ADDRESS}