server:
  port:
    10000

spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}/postgres
    username: user
    password: user

  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS}:${KAFKA_PORT}
    consumer:
      group-id: default-security-consumer

jwt:
  cookie:
    name: JwtCookie

redirect:
  prefix: ${LOCALHOST_GATEWAY_ADDRESS}

custom:
  kafka:
    address: ${KAFKA_ADDRESS}:${KAFKA_PORT}
    topic:
      request: ${TOPIC_REQUEST}
      response: ${TOPIC_RESPONSE}