server:
  port:
    10000
  cloud:
    config:
      fail-fast: true
    discovery:
      enabled: off
  datasource:
    url: jdbc:postgresql://localhost:5432/application
    username: user
    password: user

jwt:
  cookie:
    name: JwtCookie