server:
  port:
    10000

spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}/postgres
    username: user
    password: user

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_ADDRESS}
          defaultBrokerPort: ${KAFKA_PORT}

jwt:
  cookie:
    name: JwtCookie

redirect:
  prefix: ${LOCALHOST_GATEWAY_ADDRESS}

custom:
  kafka:
    address: ${KAFKA_ADDRESS}:${KAFKA_PORT}
    topic:
      request: ${TOPIC_REQUEST}
      response: ${TOPIC_RESPONSE}